from .scst_loss import ScstRewardCriterion
from .label_smoothed_cross_entropy import AdjustLabelSmoothedCrossEntropyCriterion
from .clip_scst_loss import ClipScstRewardCriterion
from .label_smoothed_encouraging_loss import AdjustLabelSmoothedEncouragingLossCriterion
from .motion_pretrain_loss import MotionPretrainCriterion
from .target_regression_loss import TargetRegressionCriterion
from .action_pred_error import ActionPredictionCriterion
